### PR TITLE
Sandboxed eval

### PR DESCRIPTION
**Pull request by Wykerd**
Using the V8 `eval` function is a massive security venerability. It gives anyone full access to everything on the host system. (For example evaluating `require('fs').readFileSync('some-sensitive-path')` or `process.exit`.)

I have sandboxed your script evaluator using isolated-vm which creates seperate V8 isolates to run untrusted user code: 

- It provides all standard ecmascript functionality one would expect from V8 but there is no node modules making it secure. 
- I have added a `send_message` function to the isolated runtimes which users can use to send a message aswell. 
- I have limited the memory and cpu time of user provided scripts to 100ms and 10mb of RAM.

I also fixed some issues with your package.json.

### CODE REVIEW

**Comment by lumap** [comment]
i mean, sure, but only the owner is able to access the eval command

**Comment by Wykerd** [comment]
oh well then its probably useless :-) If you want to add user scripting you can now though lol.

**Comment by Wykerd** [comment]
Where do you check if it is the owner running the eval command though?

**Comment by Wykerd** [comment]
I used eval on the hosted bot and it worked fine for me...

**Review by lumap — COMMENTED** [review]
Yeah, the changes to the eval commands are not useful, sorry

**Comment by Wykerd** [comment]
Oof ok but just make sure to add the check for owner though!

**Comment by lumap** [comment]
dont worry, it's already there ;)

**Comment by Wykerd** [comment]
Ok I see it now, good luck with the project further

**Comment by lumap** [comment]
thanks ^^

**Pull request closed without merging**
