### PR TITLE
Removed node_modules

### PR DESCRIPTION
**Pull request by Wykerd**
It hurt my soul seeing node_modules in your repo so I removed it for you :-)

Also it is a really bad idea to evaluate scripts with `eval` (in src/Commands/eval.js). I would recommend using something like [isolated-vm](https://github.com/laverdet/isolated-vm) instead :+1: I could help you implement it if you want me to.

### CODE REVIEW

**Comment by lumap** [comment]
Telk why didn't you removed node modules?

**Comment by Wykerd** [comment]
He added it to the gitignore file but didnt use `git rm -r` to remove it

**Comment by lumap** [comment]
he's dumb

**Comment by lumap** [comment]
Thanks for helping btw, I really appreciate that ^^

**Pull request merged**
